### PR TITLE
Boost 1.63

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by 183amir** [comment]
@jschueller do you mind updating boost in these repositories too?:
```
bob.io.audio
bob.io.base
bob.io.image
bob.io.matlab
bob.io.video
bob.ip.base
bob.ip.color
bob.ip.facedetect
bob.ip.flandmark
bob.ip.gabor
bob.learn.activation
bob.learn.boosting
bob.learn.em
bob.learn.libsvm
bob.learn.linear
bob.learn.mlp
bob.math
bob.measure
```

**Comment by jschueller** [comment]
Hello,
I dont understand why all these depend on bob.core as well as boost as bob.core already depends on boost, I think the boost dependency can be removed in all these, what do you think ?

**Comment by 183amir** [comment]
No it cannot. I have checked all of them manually. They all link against boost. So if I don't list it and `bob.core` gets updated with a new boost, all of them (still linked against old boost) will break.

**Comment by jschueller** [comment]
You cannot install two versions of boost at the same time so they wont be coinstallable anyway.

**Comment by 183amir** [comment]
That's not what I said. Let's say you only list `boost` as a dependency in `bob.core` and pin it there. First you pin it to `1.62` and compile `bob.math` with these versions without specifying `boost` as a direct dependency. Hence `bob.math` will be linked against `boost 1.62` too.
Tomorrow, you come and pin `boost` to `1.63` and compile a new version of `bob.core` (just increasing the build number here) and then `bob.math` which was linked against `boost 1.62` will break because it did not list `boost` as a dependency and `boost` was not pinned.

**Comment by jschueller** [comment]
ok

**Pull request merged**
